project:
  type: website
  output-dir: docs

website:
  title: "Shermaine's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data-visualisation.qmd
        text: Data Visualisation
      - href: interests.qmd
        text: Interests
      - href: travel.qmd
        text: My Travel Experience
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true
